### ISSUE TITLE
エラーがでてしまう

### ISSUE THREAD

**Issue by tohat** [uei/deepstation#7]
前のバージョンでmain.pyを実行した後、http://localhost:8080/にアクセスすると Errorkey 'GPU'と出てしまっていました。
また、現在のバージョン 0.2.1では、http://localhost:8080/にアクセスすると、\Anaconda2\envs\py27\lib\encodings\utf_8.py", line 16, in decode return codecs.utf_8_decode(input, errors, True)　UnicodeDecodeError: 'utf8' codec can't decode byte 0x8e in position 1083: invalid start byte　と出るようになりました。

解決策があればご教示願います。

環境は
OS windows7
GPU GT620
anaconda2.7環境下で試しています。

**Comment by hidesuke** [comment]
現在のバージョンではWindowsは正式にはサポートしておりませんが、動作検証を行いたいと思います。  
お手数ですが、エラーの詳細なログをいただけませんでしょうか？

**Comment by tohat** [comment]
ご返信ありがとうございます。
以前のバージョンでのgpuのエラーについては、バージョンを更新してしまい、ログをとっていなかったので示せません。
現在のバージョンでのエラーは以下のように出ます。　見にくくてすいません。

Critical error while processing request: /
Error:

UnicodeDecodeError('utf8', 'Traceback (most recent call last):\n  File "C:\\deepstation\\bottle.py", line 862, in _handle\n    return route.call(**args)\n  File "C:\\deepstation\\bottle.py", line 1732, in wrapper\n    rv = callback(*a, **ka)\n  File "C:\\Users\\ta1se1\\Anaconda2\\envs\\py27\\lib\\site-packages\\bottle_sqlite.py", line 87, in wrapper\n    rv = callback(*args, **kwargs)\n  File "main.py", line 84, in index\n    return bottle.template(\'index.html\', models = models.fetchall(), datasets = datasets, system_info = get_system_info(), gpu_info = get_gpu_info(), chainer_version = get_chainer_version(), python_version = get_python_version())\n  File "main.py", line 635, in get_system_info\n    df = subprocess.check_output([\'df\'])\n  File "C:\\Users\\ta1se1\\Anaconda2\\envs\\py27\\lib\\subprocess.py", line 566, in check_output\n    process = Popen(stdout=PIPE, *popenargs, **kwargs)\n  File "C:\\Users\\ta1se1\\Anaconda2\\envs\\py27\\lib\\subprocess.py", line 710, in __init__\n    errread, errwrite)\n  File "C:\\Users\\ta1se1\\Anaconda2\\envs\\py27\\lib\\subprocess.py", line 958, in _execute_child\n    startupinfo)\nWindowsError: [Error 2] \x8ew\x92\xe8\x82\xb3\x82\xea\x82\xbd\x83t\x83@\x83C\x83\x8b\x82\xaa\x8c\xa9\x82\xc2\x82\xa9\x82\xe8\x82\xdc\x82\xb9\x82\xf1\x81B\n', 1083, 1084, 'invalid start byte')

Traceback:

Traceback (most recent call last):
  File "C:\deepstation\bottle.py", line 954, in wsgi
    out = self._cast(self._handle(environ))
  File "C:\deepstation\bottle.py", line 907, in _cast
    out = self.error_handler.get(out.status_code, self.default_error_handler)(out)
  File "C:\deepstation\bottle.py", line 842, in default_error_handler
    return tob(template(ERROR_PAGE_TEMPLATE, e=res))
  File "C:\deepstation\bottle.py", line 3595, in template
    return TEMPLATES[tplid].render(kwargs)
  File "C:\deepstation\bottle.py", line 3399, in render
    self.execute(stdout, env)
  File "C:\deepstation\bottle.py", line 3386, in execute
    eval(self.co, env)
  File "<string>", line 26, in <module>
  File "C:\deepstation\bottle.py", line 3337, in <lambda>
    self._escape = lambda x: escape_func(touni(x, enc))
  File "C:\deepstation\bottle.py", line 123, in touni
    return s.decode(enc, err) if isinstance(s, bytes) else unicode(s)
  File "C:\Users\ta1se1\Anaconda2\envs\py27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8e in position 1083: invalid start byte

以上です。よろしくお願いいたします。
